TALK_TO_FILE_ROUTES:
  - name: chitchat
    utterances:
      - "hi"
      - "hello"
      - "how are you"
      - "what's up"
      - "how's it going"
      - "you're awesome"
      - "how's the weather today?"
      - "how are things going?"
      - "lovely weather today"
      - "the weather is horrendous"
      - "let's go to the chippy"

  - name: gratitude
    utterances:
      - "thanks"
      - "thank you"
      - "cheers"
      - "nice one"
      - "much appreciated"
      - "I appreciate it"
      - "I'm grateful"
      - "that means a lot"
      - "you've been a big help"
      - "I owe you one"
      - "thanks a bunch"
      - "thank you very much"
      - "love that answer"

  - name: sports_talk
    utterances:
      - "how did the game go"
      - "who won the match last night"
      - "what's the score"
      - "did you see that incredible play"
      - "who's leading the league"
      - "what are the standings"
      - "I hope our team wins"
      - "that was a great game"
      - "who is your favorite player"
      - "which team do you support"

  -name: politics_discussion
    utterances:
    - "who is the current president"
    - "what do you think about the new policy"
    - "how does the election work"
    - "what's the latest political news"
    - "who are the main candidates"
    - "what are their political platforms"
    - "how does the government function"
    - "what's your opinion on the current administration"
    - "how does this law affect us"
    - "what are the major political parties"
